'use strict';

// Generated by CoffeeScript 2.3.1
Drupal.behaviors.autocomplete_field = {
  buildData: function buildData(term, page) {
    return {
      search: term,
      limit: 20,
      offset: (page - 1) * 20
    };
  },
  processResults: function processResults(data, page) {
    return {
      results: data.values.map(function (o) {
        return {
          id: JSON.stringify(o),
          text: o.label
        };
      }),
      more: page * 20 < data.total_items
    };
  },
  initSelection: function initSelection(element, callback) {
    var data, e, p, v;
    v = element.val();
    data = {
      id: v,
      text: ''
    };
    try {
      p = JSON.parse(v);
      data.text = p.label;
    } catch (error) {
      e = error;
    }
    //# Nothing
    return callback(data);
  },
  defaultConfig: function defaultConfig() {
    return {
      minimumInputLength: 2,
      initSelection: this.initSelection,
      ajax: {
        url: Drupal.settings.autocomplete_field.endpoint,
        data: this.buildData,
        results: this.processResults,
        dataType: 'json',
        quietMillis: 250,
        params: {
          headers: {
            Authorization: Drupal.settings.autocomplete_field.apiKey
          }
        }
      }
    };
  },
  attach: function attach(context, settings) {
    var config, element_config, html_id, ref;
    ref = settings.autocomplete_field.elements;
    for (html_id in ref) {
      element_config = ref[html_id];
      config = $.extend(true, {}, this.defaultConfig(), element_config);
      $('#' + html_id, context).select2(config);
    }
  }
};